/**
 * Palais de justice et points de service de justice du Québec — table PURE.
 *
 * ⚠ PROVENANCE ET PÉREMPTION. Relevé auprès du ministère de la Justice du Québec
 *   (« Trouver un palais de justice ») le 2026-07-15 : 43 palais de justice et
 *   8 points de service. **Les palais déménagent.** Aucune sortie d'outil ne rend
 *   ces adresses sans la réserve de `GARDE_PALAIS` (src/format/render.ts) — un
 *   praticien qui signifie à une ancienne adresse rate son délai.
 *
 * Porté de Pallas Athéna (`athena/models/reference.py`, `_PALAIS`), même
 * propriétaire et même licence. Les clefs de champ sont celles d'Athéna pour que
 * le port reste vérifiable ligne à ligne contre sa source.
 *
 * `province` et `country` ne sont pas stockés : ils valent « Québec » et « Canada »
 * pour les 51 lignes, et une constante répétée 51 fois est une occasion de divergence.
 *
 * ⚠ `location_type` (« palais » / « point_de_service ») N'EST PAS la même notion que
 *   le drapeau `point_de_service` d'un GREFFE, qui marque les cours itinérantes. Les
 *   deux divergent délibérément sur les 8 points de service du MJQ. Voir greffes.ts.
 */

/** Coordonnée d'un service. Un palais en publie PLUSIEURS (une par chambre). */
export interface Contact {
  readonly service: string;
  readonly tel?: string;
  readonly courriel?: string;
}

export type TypeLieu = "palais" | "point_de_service";

export interface Palais {
  readonly name: string;
  readonly location_type: TypeLieu;
  readonly street: string;
  readonly unit: string;
  readonly city: string;
  readonly postal_code: string;
  readonly mailing_address: string;
  /**
   * Vide pour l'instant : ni Athéna ni aucune donnée ouverte ne porte les
   * coordonnées, et justice.gouv.qc.ca refuse toute requête automatisée (403).
   * À remplir depuis la page « Numéros des greffes des palais de justice et des
   * points de service de justice », enregistrée à la main. Le tableau — plutôt
   * qu'un champ `tel` unique — est délibéré : Montréal publie au moins quatre
   * numéros (chambre civile, criminelle et pénale, greffe civil, jeunesse).
   */
  readonly contacts: readonly Contact[];
}

/** Constantes non stockées : elles valent ceci pour les 51 lignes. */
export const PROVINCE = "Québec";
export const PAYS = "Canada";

/** Date du relevé auprès du MJQ. Rendue dans la réserve : elle date la donnée. */
export const RELEVE_LE = "2026-07-15";

export const PALAIS: Readonly<Record<string, Palais>> = {
  alma: {
    name: "Alma",
    location_type: "palais",
    street: "725, rue Harvey Ouest",
    unit: "",
    city: "Alma",
    postal_code: "G8B 1P5",
    mailing_address: "",
    contacts: [],
  },
  amos: {
    name: "Amos",
    location_type: "palais",
    street: "891, 3e Rue Ouest",
    unit: "",
    city: "Amos",
    postal_code: "J9T 2T4",
    mailing_address: "",
    contacts: [],
  },
  amqui: {
    name: "Amqui",
    location_type: "point_de_service",
    street: "29, boulevard Saint-Benoît Ouest",
    unit: "",
    city: "Amqui",
    postal_code: "G5J 2E4",
    mailing_address: "",
    contacts: [],
  },
  "baie-comeau": {
    name: "Baie-Comeau",
    location_type: "palais",
    street: "71, avenue Mance",
    unit: "",
    city: "Baie-Comeau",
    postal_code: "G4Z 1N2",
    mailing_address: "",
    contacts: [],
  },
  "campbells-bay": {
    name: "Campbell's Bay",
    location_type: "palais",
    street: "30, rue John",
    unit: "",
    city: "Campbell's Bay",
    postal_code: "J0X 1K0",
    mailing_address: "",
    contacts: [],
  },
  "carleton-sur-mer": {
    name: "Carleton-sur-Mer",
    location_type: "point_de_service",
    street: "17, rue Lacroix",
    unit: "",
    city: "Carleton-sur-Mer",
    postal_code: "G0C 1J0",
    mailing_address: "",
    contacts: [],
  },
  chibougamau: {
    name: "Chibougamau",
    location_type: "palais",
    street: "860, 3e Rue",
    unit: "",
    city: "Chibougamau",
    postal_code: "G8P 1P9",
    mailing_address: "",
    contacts: [],
  },
  chicoutimi: {
    name: "Chicoutimi",
    location_type: "palais",
    street: "227, rue Racine Est",
    unit: "1er étage",
    city: "Saguenay",
    postal_code: "G7H 7B4",
    mailing_address: "",
    contacts: [],
  },
  cowansville: {
    name: "Cowansville",
    location_type: "palais",
    street: "920, rue Principale",
    unit: "",
    city: "Cowansville",
    postal_code: "J2K 0E3",
    mailing_address: "",
    contacts: [],
  },
  "dolbeau-mistassini": {
    name: "Dolbeau-Mistassini",
    location_type: "point_de_service",
    street: "1420, boulevard Wallberg",
    unit: "1er étage",
    city: "Dolbeau-Mistassini",
    postal_code: "G8L 1H4",
    mailing_address: "",
    contacts: [],
  },
  drummondville: {
    name: "Drummondville",
    location_type: "palais",
    street: "1680, boulevard Saint-Joseph",
    unit: "",
    city: "Drummondville",
    postal_code: "J2C 2G3",
    mailing_address: "",
    contacts: [],
  },
  forestville: {
    name: "Forestville",
    location_type: "point_de_service",
    street: "134, route 138 Est",
    unit: "",
    city: "Forestville",
    postal_code: "G0T 1E0",
    mailing_address: "Case postale 400, Forestville (Québec) G0T 1E0",
    contacts: [],
  },
  gaspe: {
    name: "Gaspé",
    location_type: "point_de_service",
    street: "11, rue de la Cathédrale",
    unit: "bureau 101",
    city: "Gaspé",
    postal_code: "G4X 2V9",
    mailing_address: "",
    contacts: [],
  },
  gatineau: {
    name: "Gatineau",
    location_type: "palais",
    street: "17, rue Laurier",
    unit: "",
    city: "Gatineau",
    postal_code: "J8X 4C1",
    mailing_address: "",
    contacts: [],
  },
  granby: {
    name: "Granby",
    location_type: "palais",
    street: "77, rue Principale",
    unit: "bureau 1.32",
    city: "Granby",
    postal_code: "J2G 9B3",
    mailing_address: "",
    contacts: [],
  },
  "havre-aubert": {
    name: "Havre-Aubert",
    location_type: "palais",
    street: "405, chemin d'En-Haut",
    unit: "bureau 102",
    city: "Les Îles-de-la-Madeleine",
    postal_code: "G4T 9A7",
    mailing_address: "",
    contacts: [],
  },
  joliette: {
    name: "Joliette",
    location_type: "palais",
    street: "200, rue Saint-Marc",
    unit: "",
    city: "Joliette",
    postal_code: "J6E 8C2",
    mailing_address: "",
    contacts: [],
  },
  kuujjuaq: {
    name: "Kuujjuaq",
    location_type: "palais",
    street: "151, rue Siuralikuut",
    unit: "",
    city: "Kuujjuaq",
    postal_code: "J0M 1C0",
    mailing_address: "",
    contacts: [],
  },
  "la-malbaie": {
    name: "La Malbaie",
    location_type: "palais",
    street: "30, chemin de la Vallée",
    unit: "",
    city: "La Malbaie",
    postal_code: "G5A 1A3",
    mailing_address: "",
    contacts: [],
  },
  "la-sarre": {
    name: "La Sarre",
    location_type: "point_de_service",
    street: "651, 2e Rue Est",
    unit: "",
    city: "La Sarre",
    postal_code: "J9Z 2Y9",
    mailing_address: "",
    contacts: [],
  },
  "la-tuque": {
    name: "La Tuque",
    location_type: "palais",
    street: "290, rue Saint-Joseph",
    unit: "",
    city: "La Tuque",
    postal_code: "G9X 3Z8",
    mailing_address: "",
    contacts: [],
  },
  "lac-megantic": {
    name: "Lac-Mégantic",
    location_type: "palais",
    street: "5527, rue Frontenac",
    unit: "bureau 316",
    city: "Lac-Mégantic",
    postal_code: "G6B 1H6",
    mailing_address: "",
    contacts: [],
  },
  laval: {
    name: "Laval",
    location_type: "palais",
    street: "2800, boulevard Saint-Martin Ouest",
    unit: "",
    city: "Laval",
    postal_code: "H7T 2S9",
    mailing_address: "",
    contacts: [],
  },
  longueuil: {
    name: "Longueuil",
    location_type: "palais",
    street: "1111, boulevard Jacques-Cartier Est",
    unit: "",
    city: "Longueuil",
    postal_code: "J4M 2J6",
    mailing_address: "",
    contacts: [],
  },
  maniwaki: {
    name: "Maniwaki",
    location_type: "palais",
    street: "266, rue Notre-Dame",
    unit: "1er étage",
    city: "Maniwaki",
    postal_code: "J9E 2J8",
    mailing_address: "",
    contacts: [],
  },
  matane: {
    name: "Matane",
    location_type: "point_de_service",
    street: "382, avenue Saint-Jérôme",
    unit: "",
    city: "Matane",
    postal_code: "G4W 3B3",
    mailing_address: "",
    contacts: [],
  },
  "mont-laurier": {
    name: "Mont-Laurier",
    location_type: "palais",
    street: "645, rue de la Madone",
    unit: "",
    city: "Mont-Laurier",
    postal_code: "J9L 1T1",
    mailing_address: "",
    contacts: [],
  },
  montmagny: {
    name: "Montmagny",
    location_type: "palais",
    street: "110, avenue Jacques-Cartier",
    unit: "",
    city: "Montmagny",
    postal_code: "G5V 0G5",
    mailing_address: "",
    contacts: [],
  },
  montreal: {
    name: "Montréal",
    location_type: "palais",
    street: "1, rue Notre-Dame Est",
    unit: "",
    city: "Montréal",
    postal_code: "H2Y 1B6",
    mailing_address: "",
    contacts: [],
  },
  "new-carlisle": {
    name: "New Carlisle",
    location_type: "palais",
    street: "87, boulevard Gérard-D.-Lévesque",
    unit: "local 103",
    city: "New Carlisle",
    postal_code: "G0C 1Z0",
    mailing_address: "",
    contacts: [],
  },
  perce: {
    name: "Percé",
    location_type: "palais",
    street: "124, route 132",
    unit: "",
    city: "Percé",
    postal_code: "G0C 2L0",
    mailing_address: "Case postale 188, Percé (Québec) G0C 2L0",
    contacts: [],
  },
  quebec: {
    name: "Québec",
    location_type: "palais",
    street: "300, boulevard Jean-Lesage",
    unit: "",
    city: "Québec",
    postal_code: "G1K 8K6",
    mailing_address: "",
    contacts: [],
  },
  rimouski: {
    name: "Rimouski",
    location_type: "palais",
    street: "183, avenue de la Cathédrale",
    unit: "",
    city: "Rimouski",
    postal_code: "G5L 5J1",
    mailing_address: "",
    contacts: [],
  },
  "riviere-du-loup": {
    name: "Rivière-du-Loup",
    location_type: "palais",
    street: "33, rue De la Cour",
    unit: "",
    city: "Rivière-du-Loup",
    postal_code: "G5R 1J1",
    mailing_address: "",
    contacts: [],
  },
  roberval: {
    name: "Roberval",
    location_type: "palais",
    street: "750, boulevard Saint-Joseph",
    unit: "",
    city: "Roberval",
    postal_code: "G8H 2L5",
    mailing_address: "",
    contacts: [],
  },
  "rouyn-noranda": {
    name: "Rouyn-Noranda",
    location_type: "palais",
    street: "2, avenue du Palais",
    unit: "",
    city: "Rouyn-Noranda",
    postal_code: "J9X 2N9",
    mailing_address: "",
    contacts: [],
  },
  "saint-hyacinthe": {
    name: "Saint-Hyacinthe",
    location_type: "palais",
    street: "3800, avenue Cusson",
    unit: "",
    city: "Saint-Hyacinthe",
    postal_code: "J2S 8V6",
    mailing_address: "",
    contacts: [],
  },
  "saint-jean-sur-richelieu": {
    name: "Saint-Jean-sur-Richelieu",
    location_type: "palais",
    street: "109, rue Saint-Charles",
    unit: "",
    city: "Saint-Jean-sur-Richelieu",
    postal_code: "J3B 2C2",
    mailing_address: "",
    contacts: [],
  },
  "saint-jerome": {
    name: "Saint-Jérôme",
    location_type: "palais",
    street: "25, rue de Martigny Ouest",
    unit: "",
    city: "Saint-Jérôme",
    postal_code: "J7Y 4Z1",
    mailing_address: "",
    contacts: [],
  },
  "saint-joseph-de-beauce": {
    name: "Saint-Joseph-de-Beauce",
    location_type: "palais",
    street: "795, avenue du Palais",
    unit: "",
    city: "Saint-Joseph-de-Beauce",
    postal_code: "G0S 2V0",
    mailing_address: "",
    contacts: [],
  },
  "sainte-anne-des-monts": {
    name: "Sainte-Anne-des-Monts",
    location_type: "point_de_service",
    street: "10-B, boulevard Sainte-Anne Ouest",
    unit: "",
    city: "Sainte-Anne-des-Monts",
    postal_code: "G4V 1P3",
    mailing_address: "",
    contacts: [],
  },
  "salaberry-de-valleyfield": {
    name: "Salaberry-de-Valleyfield",
    location_type: "palais",
    street: "74, rue Académie",
    unit: "",
    city: "Salaberry-de-Valleyfield",
    postal_code: "J6T 0B8",
    mailing_address: "",
    contacts: [],
  },
  "sept-iles": {
    name: "Sept-Îles",
    location_type: "palais",
    street: "425, boulevard Laure",
    unit: "",
    city: "Sept-Îles",
    postal_code: "G4R 1X6",
    mailing_address: "",
    contacts: [],
  },
  shawinigan: {
    name: "Shawinigan",
    location_type: "palais",
    street: "212, 6e rue de la Pointe",
    unit: "",
    city: "Shawinigan",
    postal_code: "G9N 8B6",
    mailing_address: "",
    contacts: [],
  },
  sherbrooke: {
    name: "Sherbrooke",
    location_type: "palais",
    street: "375, rue King Ouest",
    unit: "",
    city: "Sherbrooke",
    postal_code: "J1H 6B9",
    mailing_address: "",
    contacts: [],
  },
  "sorel-tracy": {
    name: "Sorel-Tracy",
    location_type: "palais",
    street: "46, rue Charlotte",
    unit: "",
    city: "Sorel-Tracy",
    postal_code: "J3P 6N5",
    mailing_address: "",
    contacts: [],
  },
  "thetford-mines": {
    name: "Thetford Mines",
    location_type: "palais",
    street: "693, rue Saint-Alphonse Nord",
    unit: "bureau 1.23",
    city: "Thetford Mines",
    postal_code: "G6G 3X3",
    mailing_address: "",
    contacts: [],
  },
  "trois-rivieres": {
    name: "Trois-Rivières",
    location_type: "palais",
    street: "850, rue Hart",
    unit: "",
    city: "Trois-Rivières",
    postal_code: "G9A 1T9",
    mailing_address: "",
    contacts: [],
  },
  "val-dor": {
    name: "Val-d'Or",
    location_type: "palais",
    street: "900, 7e Rue",
    unit: "",
    city: "Val-d'Or",
    postal_code: "J9P 3P8",
    mailing_address: "",
    contacts: [],
  },
  victoriaville: {
    name: "Victoriaville",
    location_type: "palais",
    street: "800, boulevard Bois-Francs Sud",
    unit: "",
    city: "Victoriaville",
    postal_code: "G6P 5W5",
    mailing_address: "",
    contacts: [],
  },
  "ville-marie": {
    name: "Ville-Marie",
    location_type: "palais",
    street: "8, rue Saint-Gabriel Nord",
    unit: "",
    city: "Ville-Marie",
    postal_code: "J9V 1Z9",
    mailing_address: "",
    contacts: [],
  },
};
